app1/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls','home'))),
    path('user/', include(('caruser.urls','caruser'))),
    path('parking/', include(('parkinglot.urls','parkinglot'))),
    path('carapp/', include(('carapp.urls','carapp'))),
]

parkinglot/urls.py
from django.urls import path,include
from .views import add_ticket,inactivate_ticket,lot_detail,all_lots,success,error,parking_home,all_tickets,all_tickets_user,ticket_car
from .views import api_lots,api_tickets,mytickets,mycars,available_lots,occupied_lots
app_name='parkinglot'

urlpatterns = [
    path('add_ticket/<int:lotid>',add_ticket, name='create_ticket'),
    path('ticket_update/<int:ticketid>',inactivate_ticket, name='edit_ticket'),
    path('lot/<int:lotid>',lot_detail, name='lot_detail'),
    path('lots/',all_lots, name='all_lots'),
    path('success/',success, name='success'),
    path('error/',error, name='error'),
    path('tickets/<int:lotid>',all_tickets, name='lot_tickets'),
    path('alltickets/',all_tickets_user, name='all_tickets'),
    path('ticketcar/',ticket_car, name='ticket_car'),
    path('api/v1/lots/',api_lots, name='api_lots_v1'),
    path('api/v1/tickets/',api_tickets, name='api_tickets_v1'),
    path('api/v1/mytickets/',mytickets, name='my_tickets_v1'),
    path('api/v1/mycars/',mycars, name='my_cars_v1'),
    path('available_lots/',available_lots, name='available_lots'),
    path('occupied_lots/',occupied_lots, name='occupied_lots'),
    path('',parking_home, name='parking_home'),
]

parkinglot/models.py
from django.db import models
from django.contrib.auth.models import User
from carapp.models import Car

# Create your models here.


class LotManager(models.Manager):

    '''Get all available lots...'''

    def get_queryset(self):
        return super().get_queryset().filter(state='AVAILABLE')


class OccupiedManager(models.Manager):

    '''Get all available lots...'''

    def get_queryset(self):
        return super().get_queryset().filter(state='OCCUPIED')



class Lot(models.Model):

    '''Model for parking lot'''

    STATE=[('AVAILABLE','Available'),('OCCUPIED','Occupied'),('MANTAINENCE','Mantainence')]

    floor=models.IntegerField()
    slot=models.IntegerField()
    name=models.CharField(max_length=50)
    state=models.CharField(max_length=20,choices=STATE,default='AVAILABLE')
    objects=models.Manager()
    available_lot=LotManager()
    occupied_lot=OccupiedManager()


    def __str__(self):
        return self.name


class Ticket(models.Model):

    '''Model for ticket'''

    STATE = [('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')]

    ticketowner=models.ForeignKey(User,on_delete=models.CASCADE)
    vehicle=models.ForeignKey(Car,on_delete=models.CASCADE)
    lot=models.ForeignKey(Lot,on_delete=models.CASCADE)
    ticketstate=models.CharField(max_length=20,choices=STATE,default='ACTIVE')

    def __str__(self):
        return self.ticketstate

parkinglot/forms.py
from django.forms import ModelForm
from .models import Lot
from .models import Ticket


class LotForm(ModelForm):

    '''LotForm for creating and updating a Lot'''

    class Meta:
        model=Lot
        fields=['floor','slot','name','state']

class TicketForm(ModelForm):

    '''TicketForm for updating tickets'''

    class Meta:
        model= Ticket
        fields = ['vehicle']

class InactivateForm(ModelForm):

    '''InactivateForm for making the ticket Inactive'''

    class Meta:
        model= Ticket
        fields = ['ticketstate']

parkinglot/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Lot,Ticket
from carapp.models import Car
from django.contrib.auth.models import User
from .forms import TicketForm,LotForm,InactivateForm
from django.http import HttpResponse
from django.db import transaction
from .serializer import LotSerializer,TicketSerializer
from rest_framework.response import Response
from rest_framework.renderers import JSONRenderer
from rest_framework import status
from rest_framework import serializers
from carapp.serializer import CarSerializer
from rest_framework.decorators import renderer_classes,api_view



def lot_detail(request,lotid):

        '''Get the details of the lot and all the tickets created for this lot'''

        with transaction.atomic():
            parking_lot = Lot.objects.get(pk=lotid)
            tickets = Ticket.objects.filter(ticketowner_id=request.user.id).filter(lot_id=parking_lot.id)
            return render(request, 'parkinglot/lot_detail.html', {'parkinglot': parking_lot,'tickets':tickets})
        return HttpResponse('<h1>Error<h1>')


def all_lots(request):

    '''Get the list of lots'''
    all_lots = Lot.objects.all()
    return render(request, 'parkinglot/all_lots.html', {'all_lots': all_lots })

def available_lots(request):

    '''Get all available lots...'''
    lots=Lot.available_lot.all()
    return render(request, 'parkinglot/all_lots.html', {'all_lots': lots})

def occupied_lots(request):

    '''Get all available lots...'''
    lots=Lot.occupied_lot.all()
    return render(request, 'parkinglot/all_lots.html', {'all_lots': lots})


def all_tickets(request,lotid):

    tickets=Ticket.objects.filter(ticketowner_id=request.user.id).filter(lot_id=lotid)
    return render(request, 'parkinglot/lot_tickets.html', {'tickets': tickets})

def all_tickets_user(request):

    '''Get all the tickets created by the user'''

    tickets=Ticket.objects.filter(ticketowner_id=request.user.id)
    return render(request, 'parkinglot/tickets.html', {'tickets': tickets})

def ticket_car(request):

    '''A service to show the car and ticket info...'''

    ticket_car=Ticket.objects.select_related('vehicle').filter(ticketowner_id=request.user.id)
    return render(request, 'parkinglot/ticket_car.html', {'ticket_car': ticket_car})




def add_ticket(request,lotid):

    '''Method to create a lot ticket'''

    lot = Lot.objects.get(pk=lotid)
    cars= Car.objects.filter(carowner_id=request.user.id).filter(state='UNPARKED').all()
    if lot.state=="AVAILABLE":
            if request.method == "POST":
                with transaction.atomic():
                    lot.state='OCCUPIED'
                    lot.save()
                    ticket=Ticket()
                    ticket.lot=lot
                    ticket.ticketowner=request.user
                    ticket.vehicle=Car.objects.get(pk=request.POST.get('vehicle'))
                    ticket.vehicle='PARKED'
                    ticket.save()
                    return redirect('parkinglot:lot_detail',permanent=True,lotid=lotid)
                return redirect('parkinglot:error',permanent=True)
            form = TicketForm()
            form.fields['vehicle'].queryset=cars
            return render(request, 'parkinglot/lot_ticket.html', {'form': form })
    else:
        return HttpResponse('<h1>Lot Occupied</h1>')


def inactivate_ticket(request,ticketid):

    '''Update the tickets using this service.'''

    ticket=Ticket.objects.get(pk=ticketid)
    if request.method == "POST":
        with transaction.atomic():
            lotid=ticket.lot.id
            lot=Lot.objects.get(pk=lotid)
            lot.state='AVAILABLE'
            lot.save()
            ticket.ticketstate='INACTIVE'
            car=Car.objects.get(pk=ticket.vehicle.id)
            car.state='UNPARKED'
            ticket.save()
            car.save()
            return redirect('parkinglot:lot_detail',permanent=True,lotid=lot.id)
        return redirect('parkinglot:error', permanent=True)
    form = InactivateForm(instance=ticket)
    return render(request, 'parkinglot/inactivate_ticket.html', {'form': form})


def success(request):
    return HttpResponse('<h1>Success</h1>')

def error(request):
    return HttpResponse('<h1>Error</h1>')



def parking_home(request):

    '''Parking app home service'''

    return render(request,'parkinglot/parking_home.html')

@api_view(('GET',))
@renderer_classes((JSONRenderer,))
def api_lots(request):

    '''List of parking lots using api.'''

    all_lots=Lot.objects.all()
    lots=LotSerializer(all_lots,many=True)
    return Response(lots.data)


@api_view(('GET',))
@renderer_classes((JSONRenderer,))
def api_tickets(request):

    '''List of tickets using api.'''

    all_tickets=Ticket.objects.filter(ticketowner_id=request.user.id)
    lot_tickets=TicketSerializer(all_tickets,many=True)
    return Response(lot_tickets.data)

@api_view(('GET',))
@renderer_classes((JSONRenderer,))
def mytickets(request):

    '''List of tickets using api.'''
    with transaction.atomic():
        try:
            user=User.objects.get(id=request.user.id)
            mytickets=user.ticket_set.all()
            all_my_tickets=TicketSerializer(mytickets,many=True)
            return Response(all_my_tickets.data,status=status.HTTP_201_CREATED)
        except Exception as e:
            return Response(status=status.HTTP_400_BAD_REQUEST)

@api_view(('GET',))
@renderer_classes((JSONRenderer,))
def mycars(request):

    '''List of tickets using api.'''
    with transaction.atomic():
        try:
            user=User.objects.get(id=request.user.id)
            mycars=user.car_set.all()
            all_my_cars=CarSerializer(mycars,many=True)
            return Response(all_my_cars.data,status=status.HTTP_201_CREATED)
        except Exception as e:
            return Response(status=status.HTTP_400_BAD_REQUEST)

templates/parkinglot/all_lots.html
{% extends './parking_home.html' %}

{% block parking_contents %}
<div>
    <center><h2>Parking Lots</h2></center>
    {% for lot in all_lots %}
       <div id="content">
          <center>
             <p><b>Lot Name:</b><a href="{% url 'parkinglot:lot_detail' lotid=lot.id %}">{{lot.name}}</a></p>
             <p><b>Lot State:</b>{{lot.state}}</p>
             <p><b>Lot Floor:</b>{{lot.floor}}</p>
             <p><b>Slot:</b>{{lot.slot}}</p>
             <button style="background-color:green;color:white;margin-top:15px;margin-bottom:15px;" class="btnd"><a href="{% url 'parkinglot:lot_tickets' lotid=lot.id %}">Tickets</a></button>
          </center>
       </div>
   {% endfor %}
</div>
{% endblock %}

templates/parkinglot/inactivate_ticket.html
{% extends '../base.html' %}

{% block content %}
       <div id="register">
            <h3>Add Ticket</h3>
            <form action="" method="post">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" value="Add Car" />
            </form>
        </div>
{% endblock %}

templates/parkinglot/lot_detail.html
{% extends './parking_home.html' %}

{% block parking_contents %}
      <div>
          <div id="lotdetail">
              <h2>Lot Detail</h2>
               <h3>Lot Name:</h3>
               <p>{{parkinglot.name}}</p>
               <h3>Lot State:</h3>
               <p>{{parkinglot.state}}</p>
               <h3>Lot Floor:</h3>
               <p>{{parkinglot.floor}}</p>
               <h3>Slot:</h3>
               <p>{{parkinglot.slot}}</p>
          </div>
          <div id="alltickets">
              <h3>All Tickets</h3>
              {% for ticket in tickets %}
                   <div id="ticket">
                      <center>
                         <p><b>Ticket Owner:</b><a href="">{{ticket.ticketowner.username}}</a></p>
                         <p><b>Vehicle Name:</b>{{ticket.vehicle.carname}}</p>
                         <p><b>State :</b>{{ticket.ticketstate}}</p>
                      </center>
                   </div>
              {% endfor %}
          </div>
      </div>
{% endblock %}

templates/parkinglot/lot_ticket.html
{% extends '../base.html' %}

{% block content %}
   <div class="register">
            <h3>Add Ticket</h3>
            <form action="" method="post">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" value="Add Car" />
            </form>
   </div>
{% endblock %}

templates/parkinglot/lot_tickets.html
{% extends './parking_home.html' %}
{% block parking_contents %}
      <div>
          <div id="alltickets">
              <h3>All Tickets</h3>
              {% for ticket in tickets %}
                   <div id="ticket" style="margin-right:15px;margin-left:15px;">
                      <center>
                         <p><b>Ticket Owner:</b><a href="">{{ticket.ticketowner.username}}</a></p>
                         <p><b>Vehicle Name:</b>{{ticket.vehicle.carname}}</p>
                         <p><b>State :</b>{{ticket.ticketstate}}</p>
                          <button style="background-color:green;color:white;margin-top:15px;margin-bottom:15px;" class="btnd"><a href="{% url 'parkinglot:edit_ticket' ticketid=ticket.id %}">Tickets</a></button>
                      </center>
                   </div>
              {% endfor %}
          </div>
      </div>
{% endblock %}

templates/parkinglot/parking_home.html
{% extends '../base.html' %}

{% block content %}
<div>
  <div class="parking">
       <a href="/parking/lots/">Lots</a>
       <a href="/parking/alltickets/">Tickets</a>
       <a href="/parking/ticketcar/">Car-Ticket-Info</a>
       <a href="/parking/available_lots/">Available-Lots</a>
       <a href="/parking/occupied_lots/">Occupied-Lots</a>
       <a href="/carapp/">Car-App</a>
       <a href="/user/home/">Home</a>
  </div>
  <div  class="contentpanel">
    {% block parking_contents %}
    {% endblock %}
  </div>
</div>
{% endblock %}

templates/parkinglot/ticket_car.html
{% extends './parking_home.html' %}

{% block parking_contents %}
<div>
    <center><h2>Car and ticket details</h2></center>
       <div id="tablespace">
          <center>
             <table id="mytable" style="width:30%;border:1px solid black;border-collapse:collapse;">
                <tr>
                    <th>Ticket ID</th>
                    <th>Car Name</th>
                    <th>Car Number</th>
                    <th>Ticket State</th>
                    <th>Ticket Owner</th>
                    <th>Ticket Owner Mail</th>
                    <th>Registered Date</th>
                    <th>Car Color</th>
                </tr>
                {% for tc in ticket_car %}
                <tr>
                   <td>{{tc.id}}</td>
                   <td>{{tc.vehicle.carname}}</td>
                   <td>{{tc.vehicle.carnumber}}</td>
                   <td>{{tc.ticketstate}}</td>
                    <td>{{tc.ticketowner.username}}</td>
                    <td>{{tc.ticketowner.email}}</td>
                    <td>{{tc.vehicle.registereddate}}</td>
                    <td>{{tc.vehicle.carcolor}}</td>
                </tr>
                {% endfor %}
            </table>
           </center>
       </div>
</div>
{% endblock %}

templates/parkinglot/tickets.html
{% extends './parking_home.html' %}
{% block parking_contents %}
      <div>
          <div>
              <h3>All Tickets</h3>
              {% for ticket in tickets %}
                   <div id="ticket" style="margin-right:15px;margin-left:15px;">
                      <center>
                         <p><b>Ticket Owner:</b><a href="">{{ticket.ticketowner.username}}</a></p>
                         <p><b>Vehicle Name:</b>{{ticket.vehicle.carname}}</p>
                         <p><b>State :</b>{{ticket.ticketstate}}</p>
                          <button style="background-color:green;color:white;margin-top:15px;margin-bottom:15px;" class="btnd"><a href="{% url 'parkinglot:edit_ticket' ticketid=ticket.id %}">STATE</a></button>
                      </center>
                   </div>
              {% endfor %}
          </div>
      </div>
{% endblock %}