app1/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls','home'))),
    path('user/', include(('caruser.urls','caruser'))),
    path('parking/', include(('parkinglot.urls','parkinglot'))),
    path('carapp/', include(('carapp.urls','carapp'))),
]

carapp/urls.py
from django.urls import path,include
from .views import add_car,get_all_cars,car_detail,edit_car,success,error,car_app_home,api_user_cars
from .views import get_all_cars_parked,get_all_cars_unparked

app_name='carapp'

urlpatterns = [
    path('add_car/',add_car, name='add_car'),
    path('cars/',get_all_cars, name='all_car'),
    path('car/<int:carid>',car_detail, name='car_detail'),
    path('success/',success, name='success'),
    path('error/',error, name='error'),
    path('edit/<int:carid>',edit_car, name='edit_car'),
    path('parkedcar/',get_all_cars_parked, name='parked_car'),
    path('unparkedcar/',get_all_cars_unparked, name='unparked_car'),
    path('api/v1/cars/',api_user_cars, name='all_car_user_api_v1'),
    path('',car_app_home, name='car_home'),
]

carapp/models.py
from django.db import models
from django.contrib.auth.models import User
from carservice.models import CarService
from django.db import transaction

# Create your models here.


class CarGroup(models.Model):

    '''Car group for associating car with a service.'''

    groupname=models.CharField(max_length=100)
    services=models.ForeignKey(CarService,on_delete=models.CASCADE)


    def __str__(self):
        return self.groupname

class ParkedCarManager(models.Manager):

    '''Get all parked cars...'''

    def get_queryset(self):
        return super().get_queryset().filter(state='PARKED')



class UnParkedCarManager(models.Manager):

    '''Get all unparked cars...'''

    def get_queryset(self):
        return super().get_queryset().filter(state='UNPARKED')


class Car(models.Model):

    '''Model for a car'''

    STATE = [('PARKED', 'Parked'), ('UNPARKED', 'Unparked')]

    carname=models.CharField(max_length=100)
    carowner=models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    carnumber=models.CharField(max_length=100)
    carcolor=models.CharField(max_length=20,default='NOCOLOR')
    registereddate=models.DateTimeField(auto_now=True,blank=False)
    state= models.CharField(max_length=20,choices=STATE,default='UNPARKED')
    cargroup=models.ForeignKey(CarGroup,on_delete=models.CASCADE,default=1)
    objects=models.Manager()
    parkedcar=ParkedCarManager()
    unparkedcar=UnParkedCarManager()

    def __str__(self):
        return self.carname

carapp/forms.py
from django.forms import ModelForm
from .models import Car


class CarForm(ModelForm):

    '''Carform to populate the car model'''

    class Meta:
        model=Car
        fields=['carname','carnumber','carcolor']

class CarUpdateForm(ModelForm):

    '''Carform to populate the car model'''

    class Meta:
        model=Car
        fields=['carname','carcolor','cargroup']

carapp/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Car
from django.contrib.auth.models import User
from .forms import CarForm,CarUpdateForm
from django.http import HttpResponse
from .serializer import CarSerializer
from rest_framework.response import Response
from rest_framework.renderers import JSONRenderer
from caruser.serializer import UserSerializer
from rest_framework.decorators import renderer_classes,api_view
from django.db import transaction
from .models import CarGroup
from django.contrib.auth.models import Group

# Create your views here.


def get_all_cars(request):

    '''Get all the cars of the user'''

    cars=Car.objects.filter(carowner_id=request.user.id)
    return render(request,'carapp/cars.html',{'cars':cars})


def get_all_cars_parked(request):

    '''Get all the parked cars of the user'''

    cars=Car.parkedcar.filter(carowner_id=request.user.id).all()
    return render(request,'carapp/cars.html',{'cars':cars})


def get_all_cars_unparked(request):

    '''Get all the unparked cars of the user'''

    cars=Car.unparkedcar.filter(carowner_id=request.user.id).all()
    return render(request,'carapp/cars.html',{'cars':cars})

def car_detail(request,carid):

    '''Method to get the details of the car'''

    car=Car.objects.get(pk=carid)
    return render(request,'carapp/car_detail.html',{'car':car})

def add_car(request):

        '''Method to add a new car'''

        if request.method == "POST":
            with transaction.atomic():
                form=CarForm(request.POST)
                car=Car()
                car.carowner=request.user
                car.carname=request.POST.get('carname')
                car.carcolor=request.POST.get('carcolor')
                car.carnumber = request.POST.get('carnumber')
                car.cargroup=CarGroup.objects.get(groupname=request.user.groups.all()[0].name)
                car.save()
                return redirect('carapp:car_detail',carid=car.id)
            return HttpResponse('<h1>Error</h1>')

        form = CarForm()
        return render(request, 'carapp/add_car.html', {'form': form})


def edit_car(request,carid):

    '''Method to add a new car'''
    groups=Group.objects.all()
    car=Car.objects.get(pk=carid)
    if request.method == "POST":
        car.carname = request.POST.get('carname')
        car.carcolor = request.POST.get('carcolor')
        car.save()
        return redirect('carapp:car_detail',carid=car.id)

    form = CarUpdateForm(instance=car)
    form.fields['cargroup'].queryset=groups
    return render(request, 'carapp/update_car.html', {'form': form})



def success(request):

    '''Service for success mesage:'''

    return HttpResponse('<h1>Success</h1>')

def error(request):

    '''Service for error message:'''

    return HttpResponse('<h1>Error</h1>')

def car_app_home(request):

    '''Car app home service'''

    return render(request,'carapp/carapp_home.html')


@api_view(('GET',))
@renderer_classes((JSONRenderer,))
def api_user_cars(request):

    '''App users list using api view and json renderer'''

    all_cars_user=Car.objects.filter(carowner_id=request.user.id)
    cars=CarSerializer(all_cars_user,many=True)
    return Response(cars.data)

templates/carapp/add_car.html
{% extends './carapp_home.html' %}

{% block car_contents %}
   <div>
        <h3>Add Car</h3>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Add Car" />
        </form>
   </div>
{% endblock %}

templates/carapp/car_detail.html
{% extends './carapp_home.html' %}

{% block car_contents %}
       <center>
           <div>
                <div id="cardetail">
                    <center>
                          <h3>Car Detail</h3>
                          <p><b>Car Name:</b>{{car.carname}}</p>
                          <p><b>Car Owner:</b>{{car.carowner.username}}</p>
                          <p><b>Car Number:</b>{{car.carnumber}}</p>
                          <p><b>Car Color:</b>{{car.carcolor}}</p>
                          <p><b>Car State:</b>{{car.state}}</p>
                          <p><b>Registered Date:</b>{{car.registereddate}}</p>
                    </center>
                </div>
        </div>
       </center>
{% endblock %}

templates/carapp/carapp_home.html
{% extends '../base.html' %}

{% block content %}
<div>
  <div class="parking">
       <a href="/carapp/cars/">Cars</a>
       <a href="/carapp/add_car/">Add Car</a>
       <a href="/carapp/parkedcar/">Parked Car</a>
       <a href="/carapp/unparkedcar/">Unparked Car</a>
       <a href="/parking/">Parking-App</a>
       <a href="/user/home/">Home</a>
  </div>
  <div  class="contentpanel">
    {% block car_contents %}
    {% endblock %}
  </div>
</div>
{% endblock %}

templates/carapp/cars.html
{% extends './carapp_home.html' %}

{% block car_contents %}
<div>
    <center><h2>Your Cars</h2></center>
    {% for car in cars %}
       <div id="carcontent">
          <center>
                   <p><b>Car Name:</b><a href="{% url 'carapp:car_detail' carid=car.id %}">{{car.carname}}</a></p>
                   <p><b>Car Owner:</b>{{car.carowner.username}}</p>
                   <p><b>Car Number:</b>{{car.carnumber}}</p>
                   <p><b>Car Color:</b>{{car.carcolor}}</p>
                   <p><b>Registered Date:</b>{{car.registereddate}}</p>
                   <p><b>Car State:</b>{{car.state}}</p>
                   <button style="background-color:green;color:white;margin-top:15px;margin-bottom:15px;" class="btnd"><a href="{% url 'carapp:edit_car' carid=car.id %}">Edit Car</a></button>
          </center>
       </div>
   {% endfor %}
</div>
{% endblock %}

templates/carapp/update_car.html
{% extends './carapp_home.html' %}

{% block car_contents %}
   <div>
        <h3>Add Car</h3>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Add Car" />
        </form>
   </div>
{% endblock %}